# TODO: This workflow ensures the code we deploy:
# 1. Is well formatted
# 2. Is Linted

name: basic-Workflow-validation
on:
  pull_request:
    branches: ["main"]
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is a test"
