name: CI-check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - "A[0-9][0-9]/[0-9][0-9]"

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Set up PostgreSQL database and user
        run: |
          PGPASSWORD=postgres psql -h localhost -U postgres << EOF
          CREATE DATABASE $DB_NAME;
          CREATE USER $DB_USER WITH ENCRYPTED PASSWORD '$DB_PASSWORD';
          GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DB_USER;
          EOF
        env:
          PGPASSWORD: postgres
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      - name: Run unit tests
        run: npm run test:github
        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: localhost
          DB_PORT: 5432
