# .github/workflows/build-image.yml

name: Build Packer Image

on:
  push:
    branches:
      - main
      - "A[0-9][0-9]/[0-9][0-9]"

jobs:
  packer_image_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build Application Artifact
        run: |
          echo "buidld section here"

      - name: Run Packer Build
        run: |
          packer build packer.pkr.hcl
