name: packer status run

on:
  pull_request:
    branches: ["main"]

jobs:
  packerstatus:
    runs-on: ubuntu-latest
    name: Run Packer

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Packer
        uses: hashicorp/setup-packer@main

      - name: Run Packer fmt
        run: |
          packer fmt -check ./packer/aws-ubuntu.pckr.hcl
          if [[ $(git diff --stat) != '' ]]; then
            echo "Packer template is not formatted correctly."
            exit 1
          fi

      - name: Run Packer validate
        run: |
          packer validate ./packer/aws-ubuntu.pckr.hcl
