name: packer status run

on:
  pull_request:
    branches:
      - "main"

  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  packer_format_validate:
    runs-on: ubuntu-latest
    name: Packer Format

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List repository contents
        run: ls -R

      - name: Set up Packer
        uses: hashicorp/setup-packer@main
        with:
          version: "latest"

      - name: Run `packer init`
        id: init
        run: |
          cd packer
          packer init .

      - name: Run Packer fmt
        run: |
          packer fmt -check -var aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID_CLI }} \
                          -var aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY_CLI }} \
                          -var aws_region=${{ secrets.AWS_REGION }} \
                          -var instance_type=${{ secrets.INSTANCE_TYPE }} \
                          packer/aws-ubuntu.pkr.hcl

      - name: Run Packer validate
        run: |
          packer validate -var aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID_CLI }} \
                          -var aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY_CLI }} \
                          -var aws_region=${{ secrets.AWS_REGION }} \
                          -var instance_type=${{ secrets.INSTANCE_TYPE }} \
                          packer/aws-ubuntu.pkr.hcl
