name: Build Packer Image

on:
  pull_request:
    branches: ["main"]
    types: ["closed"]

jobs:
  packer_image_build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip nodejs npm postgresql postgresql-contrib

      - name: Start PostgreSQL Service
        run: sudo service postgresql start

      - name: Configure PostgreSQL User and Database
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}
        run: |
          sudo -u postgres psql -c "CREATE USER $POSTGRES_USER WITH PASSWORD '$POSTGRES_PASSWORD';"
          sudo -u postgres psql -c "ALTER USER $POSTGRES_USER CREATEDB;"
          sudo -u postgres psql -c "CREATE DATABASE $POSTGRES_DB OWNER $POSTGRES_USER;"
          echo "PostgreSQL setup completed."

      - name: Build and Test Application
        run: |
          npm install
          npm run test:github

      - name: Package Application
        run: zip -r webapp.zip .

      - name: Set up Packer
        uses: hashicorp/setup-packer@main
        with:
          version: "latest"

      - name: Run Packer Build
        run: |
          packer build packer/packer.pkr.hcl
